# Generated by Django 5.1.3 on 2024-11-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CustomerID", models.CharField(max_length=100, unique=True)),
                ("Pw", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=100)),
                ("Birth", models.CharField(max_length=6)),
                ("SerialNum", models.CharField(max_length=1)),
                ("Phone", models.CharField(max_length=11)),
            ],
            options={
                "db_table": "usertable",
            },
        ),
    ]
