# Generated by Django 5.1.3 on 2024-11-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("birth", models.DateField()),
                ("serial", models.CharField(max_length=7)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
